"""Compile untrusted visitor text into a deliberately small FTS5 query language.

SQLite FTS5 accepts a rich query syntax. The public question must never be
treated as that syntax, so this module returns either a parameter value for a
bounded exact-value fallback or a query made exclusively of generated quoted
phrases joined by generated ``AND`` operators.
"""

from __future__ import annotations

import unicodedata
from dataclasses import dataclass
from enum import StrEnum

MIN_FTS_QUERY_CHARACTERS = 3
MAX_FTS_TERMS = 32
MAX_FTS_TERM_CHARACTERS = 128


class FtsQueryMode(StrEnum):
    """The safe retrieval mode chosen for normalized visitor text."""

    NO_QUERY = "no_query"
    SHORT_EXACT = "short_exact"
    MATCH = "match"


@dataclass(frozen=True, slots=True)
class CompiledFtsQuery:
    """A safe FTS5 ``MATCH`` parameter or a literal short-value fallback.

    ``match_expression`` is always generated by this module. Callers pass it
    as a bound SQLite value and must not concatenate it into SQL.
    """

    mode: FtsQueryMode
    normalized_text: str
    terms: tuple[str, ...]
    match_expression: str | None
    exact_value: str | None


def compile_fts_query(question: str) -> CompiledFtsQuery:
    """Compile untrusted text without allowing any caller-supplied FTS syntax.

    Empty or control-only input produces :attr:`FtsQueryMode.NO_QUERY`.
    Questions shorter than three normalized Unicode scalar values use the
    caller's bounded exact-value fallback. Other input becomes a conjunction
    of generated, quoted phrases; user quotation marks are removed before
    query generation so no user character can terminate a generated phrase.

    Raises:
        TypeError: If ``question`` is not text.
        ValueError: If the input exceeds the primitive's bounded term limits.
    """
    if not isinstance(question, str):
        raise TypeError("question must be a string")

    normalized = _normalize_question(question)
    if not normalized:
        return CompiledFtsQuery(
            mode=FtsQueryMode.NO_QUERY,
            normalized_text="",
            terms=(),
            match_expression=None,
            exact_value=None,
        )

    if len(normalized) < MIN_FTS_QUERY_CHARACTERS:
        return CompiledFtsQuery(
            mode=FtsQueryMode.SHORT_EXACT,
            normalized_text=normalized,
            terms=(normalized,),
            match_expression=None,
            exact_value=normalized,
        )

    terms = _compile_terms(normalized)
    if not terms:
        return CompiledFtsQuery(
            mode=FtsQueryMode.NO_QUERY,
            normalized_text=normalized,
            terms=(),
            match_expression=None,
            exact_value=None,
        )

    return CompiledFtsQuery(
        mode=FtsQueryMode.MATCH,
        normalized_text=normalized,
        terms=terms,
        match_expression=" AND ".join(_quote_phrase(term) for term in terms),
        exact_value=None,
    )


def _normalize_question(question: str) -> str:
    """Normalize to NFC, replacing every Unicode control with one separator."""
    nfc_question = unicodedata.normalize("NFC", question)
    without_controls = "".join(
        " " if unicodedata.category(character).startswith("C") else character
        for character in nfc_question
    )
    return " ".join(without_controls.split())


def _compile_terms(normalized: str) -> tuple[str, ...]:
    """Retain bounded searchable fragments while stripping phrase delimiters."""
    terms: list[str] = []
    for raw_term in normalized.split(" "):
        # A user quote is the one FTS5 phrase delimiter. Dropping it before
        # wrapping the term in a generated quote makes phrase termination
        # impossible, even when the question is deliberately injection-shaped.
        term = raw_term.replace('"', "").replace("*", "")
        if not any(character.isalnum() for character in term):
            continue
        if len(term) > MAX_FTS_TERM_CHARACTERS:
            raise ValueError("query terms must not exceed 128 characters")
        terms.append(term)
        if len(terms) > MAX_FTS_TERMS:
            raise ValueError("query must not contain more than 32 searchable terms")
    return tuple(terms)


def _quote_phrase(term: str) -> str:
    """Return a generated FTS5 phrase after delimiter removal in ``_compile_terms``."""
    return f'"{term}"'
